apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-employ-positions-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-employ-positions-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /get-employ-positions
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /get-employ-positions
