include:
- ./func/*
kind: ArchiveUploadSpec
name: func-b1qo

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-employ-positions-fn-74bc292a-79ca-4f6c-a02b-cb847aec7b41
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: get-employ-positions-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-b1qo
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-10-07T10:55:50Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-employ-positions-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: get-employ-positions-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_employ_positions
    packageref:
      name: get-employ-positions-fn-74bc292a-79ca-4f6c-a02b-cb847aec7b41
      namespace: default
  requestsPerPod: 10000
  resources: {}
